openapi: 3.0.3

info:
  title: RTP Activation API.
  version: 1.0.0
  description: |
    API to handle RTP activations initiated by the Payer's RTP Service Provider.
  contact:
    name: PagoPA S.p.A.
    email: rtp@pagopa.it

servers:
  - description: Development/Test
    url: localhost:8080
    x-internal: true

tags:
  - name: create
    description: Create operation.
  - name: read
    description: Read operation.
  - name: update
    description: Update operation.
  - name: delete
    description: Delete operation.

paths:
  /activations:
    post:
      operationId: activate
      summary: RTP activation initiated by the Payer's RTP Service Provider.
      description: |
        The operation is used by Payer's RTP Service Provider to enable the
        Payee's RTP Service Provider to send RTP messages to the Payer's RTP
        Service Provider.
        
        When the operation is used by not-admin subject, the system verifies
        that the Payer's RTP Service Provider ID matches the subject claim of
        the access token. `403 Forbidden` is returned on mismatch.
        
        `409 Conflict` is returned if an activation with the same Payer's ID
        already exists.
      tags: [create]
      security:
        - oAuth2: [admin_rtp_activations, write_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
      requestBody:
        $ref: '#/components/requestBodies/CreateOrUpdateActivation'
      responses:
        "201":
          #description: Created.
          $ref: '#/components/responses/CreateActivation'
        "400":
          #description: Bad request.
          $ref: '#/components/responses/Error'
        "401":
          #description: Wrong credentials.
          $ref: '#/components/responses/UnauthorizedError'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/ForbiddenError'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/GenericError'
        "409":
          #description: Conflict.
          $ref: '#/components/responses/ConflictError'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/GenericError'
        "429":
          #description: Too many request.
          $ref: '#/components/responses/GenericError'
        "500":
          #description: Server error.
          $ref: '#/components/responses/GenericError'
        default:
          #description: Unexpected error.
          $ref: '#/components/responses/GenericError'

    get:
      operationId: getActivations
      summary: Returns RTP activations.
      description: |
        The operation returns all the RTP activations stored by the system.
        
        When the operation is used by not-admin subject, the system returns
        the RTP activations which have the Payer's RTP Service Provider ID that
        matches the subject claim of the access token.
      tags: [read]
      security:
        - oAuth2: [admin_rtp_activations, read_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        "200":
          #description: Ok.
          $ref: '#/components/responses/PageOfActivations'
        "400":
          #description: Bad request.
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid.
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden.
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request.
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error.
          $ref: '#/components/responses/Error'
        default:
          #description: Unexpected error.
          $ref: '#/components/responses/Error'

  /activations/{activationId}:
    get:
      operationId: getActivation
      summary: Returns a RTP activation.
      description: |
        The operation finds a RTP activation by its ID.
        
        When the operation is used by not-admin subject, the system returns
        the RTP activation only if its Payer's RTP Service Provider ID matches
        the subject claim of the access token, otherwise `404 Not Found` is
        returned.
      tags: [read]
      security:
        - oAuth2: [admin_rtp_activations, read_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/ActivationId'
      responses:
        "200":
          #description: Found.
          $ref: '#/components/responses/Activation'
        "400":
          #description: Bad request.
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid.
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden.
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found.
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request.
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error.
          $ref: '#/components/responses/Error'
        default:
          #description: Unexpected error.
          $ref: '#/components/responses/Error'

    put:
      operationId: updateActivation
      summary: Updates a RTP activation.
      description: |
        The operation updates a RTP activation searching it by its ID.
        
        When the operation is used by not-admin subject:
          - the system returns `404 Not Found` if the Payer's RTP Service
            Provider ID of the activation doesn't match the subject claim of
            the access token;
          - the system returns `403 Forbidden` if the provided value of Payer's
            RTP Service doesn't match the subject claim of the access token.
      tags: [update]
      security:
        - oAuth2: [admin_rtp_activations, write_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/ActivationId'
      requestBody:
        $ref: '#/components/requestBodies/CreateOrUpdateActivation'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Wrong credentials
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          #description: Unexpected error
          $ref: '#/components/responses/Error'

    delete:
      operationId: deleteActivation
      summary: Deletes a RTP activation.
      description: |
        The operation deletes a RTP activation searching it by its ID.
        
        When the operation is used by not-admin subject, the system returns
        `404 Not Found` if the Payer's RTP Service Provider ID of the activation
        doesn't match the subject claim of the access token.
      tags: [delete]
      security:
        - oAuth2: [admin_rtp_activations, write_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/ActivationId'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          #description: Unexpected error
          $ref: '#/components/responses/Error'

    patch:
      operationId: takeoverActivation
      summary: Takes over a RTP activation.
      description: |
        The operation updates the Payer's RTP Service Provider ID of a RTP
        activation searching it by its ID.
      tags: [update]
      security:
        - oAuth2: [admin_rtp_activations, write_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/ActivationId'
      requestBody:
        $ref: '#/components/requestBodies/TakeoverActivation'
      responses:
        "204":
          #description: No content
          $ref: '#/components/responses/NoContent'
        "400":
          #description: Bad request
          $ref: '#/components/responses/Error'
        "401":
          #description: Wrong credentials
          $ref: '#/components/responses/Error'
        "403":
          #description: Forbidden
          $ref: '#/components/responses/Error'
        "404":
          #description: Not found
          $ref: '#/components/responses/Error'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/Error'
        "415":
          #description: Unsupported media type. Did you provide application/json?
          $ref: '#/components/responses/Error'
        "429":
          #description: Too many request
          $ref: '#/components/responses/Error'
        "500":
          #description: Server error
          $ref: '#/components/responses/Error'
        default:
          #description: Unexpected error
          $ref: '#/components/responses/Error'

  /activations/payer:
    get:
      operationId: findActivationByPayerId
      summary: Finds a RTP activation by Payer ID.
      description: |
        The operation finds RTP activation by Payer ID.
        
        When the operation is used by not-admin subject, the system returns
        the RTP activation with the Payer's RTP Service Provider ID that
        matches the subject claim of the access token.
      tags: [read]
      security:
        - oAuth2: [admin_rtp_activations, read_rtp_activations]
      parameters:
        - $ref: '#/components/parameters/RequestId'
        - $ref: '#/components/parameters/Version'
        - $ref: '#/components/parameters/PayerId'
      responses:
        "200":
          #description: Ok.
          $ref: '#/components/responses/Activation'
        "400":
          #description: Bad request.
          $ref: '#/components/responses/Error'
        "401":
          #description: Access token is missing or invalid.
          $ref: '#/components/responses/UnauthorizedError'
        "403":
          #description: Forbidden.
          $ref: '#/components/responses/ForbiddenError'
        "406":
          #description: Not acceptable. Did you require application/json?
          $ref: '#/components/responses/GenericError'
        "429":
          #description: Too many request.
          $ref: '#/components/responses/GenericError'
        "500":
          #description: Server error.
          $ref: '#/components/responses/GenericError'
        default:
          #description: Unexpected error.
          $ref: '#/components/responses/GenericError'

components:
  # ============================================================================
  # Schemas.
  # ============================================================================
  schemas:
    # --------------------------------------------------------------------------
    # Basic types for CORS stuff.
    # --------------------------------------------------------------------------
    AccessControlAllowOrigin:
      description: |
        Indicates whether the response can be shared with requesting code from
        the given origin.
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048


    WWWAuthenticate:
      description: |
        Indicates the authentication scheme(s) and parameters required to access a protected resource.
      type: string
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048
    # --------------------------------------------------------------------------
    # Basic types for rate limit handling.
    # --------------------------------------------------------------------------
    RateLimitLimit:
      description: The number of allowed requests in the current period.
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    RateLimitReset:
      description: The number of seconds left in the current period.
      type: integer
      format: int32
      minimum: 1
      maximum: 60

    RetryAfter:
      description: |
        The number of seconds to wait before allowing a follow-up request.
      type: integer
      format: int32
      minimum: 1
      maximum: 240

    # --------------------------------------------------------------------------
    # Basic types for paging.
    # --------------------------------------------------------------------------
    PageNumber:
      description: Number of the page.
      type: integer
      format: int32
      minimum: 0
      maximum: 2147483647
      example: 1

    PageSize:
      description: Size of the page.
      type: integer
      format: int32
      minimum: 1
      maximum: 128
      example: 20

    TotalElements:
      description: Total elements.
      type: integer
      format: int64
      minimum: 0
      maximum: 9223372036854775807
      example: 20

    TotalPages:
      description: Total pages.
      type: integer
      format: int64
      minimum: 0
      maximum: 9223372036854775807
      example: 20

    # --------------------------------------------------------------------------
    # Basic types for error handling.
    # --------------------------------------------------------------------------
    ErrorCode:
      description: Error code.
      type: string
      pattern: "^[A-F0-9]{9}$"
      minLength: 9
      maxLength: 9
      example: "01000000F"

    ErrorDescription:
      description: Error description.
      type: string
      pattern: "^[ -~]{0,256}$"
      minLength: 0
      maxLength: 256
      example: "Wrong party identifier"

    StatusCode:
      description: HTTP status code.
      type: integer
      format: int32
      minimum: 0
      maximum: 999
      example: 401

    # --------------------------------------------------------------------------
    # Basic types for technical stuff.
    # --------------------------------------------------------------------------
    ActivationId:
      description: Identifier of the RTP activation resource.
      type: string
      format: uuid
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      minLength: 36
      maxLength: 36
      example: "d0d654e6-97da-4848-b568-99fedccb642b"

    ActivationLocation:
      description: URL of the RTP activation resource.
      type: string
      format: uri
      pattern: "^[ -~]{1,2048}$"
      minLength: 1
      maxLength: 2048
      example: "https://rtp.cstar.pagopa.it/activations/d0d654e6-97da-4848-b568-99fedccb642b"

    RequestId:
      description: Identifier of the request.
      type: string
      format: uuid
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      minLength: 36
      maxLength: 36
      example: "bd615b4a-066d-443e-8dd2-a28a39931fef"

    Version:
      description: Version of the required API.
      type: string
      pattern: "^[ -~]{1,64}$"
      minLength: 1
      maxLength: 64
      example: "v1"

    # --------------------------------------------------------------------------
    # Domain specific basic types.
    # --------------------------------------------------------------------------
    Bic:
      description: Bank Identification Code.
      type: string
      pattern: "^[A-Z0-9]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3}){0,1}$"
      minLength: 8
      maxLength: 11
      example: "UNCRITMM"
        
    EffectiveActivationDate:
      description: |
        Effective activation date (B035).
                
        Date and time at which activation has been stored.
      type: string
      format: date-time
      minLength: 19
      maxLength: 29
      pattern: "^((?:(\\d{4}-\\d{2}-\\d{2})T(\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?))(Z|[\\+-]\\d{2}:\\d{2})?)$"
      example: "2024-10-30T16:39:34.123+01:00"

    FiscalCode:
      description: |
        Fiscal code.
        
        It is used as identifier of the Payer (P009) and of the Payee (E005).
      type: string
      pattern: "^(([A-Z]{6}\\d{2}[A-Z]\\d{2}[A-Z]\\d{3}[A-Z])|(\\d{11}))$"
      minLength: 11
      maxLength: 16
      example: "RSSMRA85T10A562S"

    Vat:
      description: |
        Value Added Tax is an identification number allocated to a party.
      type: string
      pattern: "^[0-9]{11}$"
      minLength: 11
      maxLength: 11
      example: "12345678911"

    PartyId:
      description: |
        Unique and unambiguous identification of a party.

        It is used as identifier of the Payer's RTP Service Provider (N001) and
        for Payee's RTP Service Provider (N002).

        A Service Provider is identified by its BIC (Bank Identification Code)
        if it is a PSP, otherwise it is identified by its VAT identification number 
        (Value Added Tax id).
      type: string
      pattern: "(^([A-Z0-9]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3}){0,1})$)|(^[0-9]{11}$)"

    # --------------------------------------------------------------------------
    # Complex types for paging.
    # --------------------------------------------------------------------------
    PageMetadata:
      description: Metadata of a page of data.
      type: object
      additionalProperties: false
      properties:
        totalElements:
          $ref: '#/components/schemas/TotalElements'
        totalPages:
          $ref: '#/components/schemas/TotalPages'
        page:
          $ref: '#/components/schemas/PageNumber'
        size:
          $ref: '#/components/schemas/PageSize'
      required:
        - totalElements
        - totalPages
        - page
        - size
      example:
        totalElements: 198
        totalPages: 10
        page: 5
        size: 20

    # --------------------------------------------------------------------------
    # Complex type for error handling.
    # --------------------------------------------------------------------------
    Error:
      description: Error details.
      type: object
      additionalProperties: false
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        description:
          $ref: '#/components/schemas/ErrorDescription'
      required:
        - code
        - description
      example:
        code: "01000000F"
        description: "Wrong party identifier"

    Errors:
      description: List of errors.
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          minItems: 1
          maxItems: 32
          items:
            $ref: '#/components/schemas/Error'
      required:
        - errors
      example:
        errors:
          - code: "01000000F"
            description: "Wrong party identifier"

    GenericError:
      description: Generic error.
      type: object
      additionalProperties: false
      properties:
        timestamp:
          type: string
          format: date-time
          description: The time the error occurred.
        path:
          type: string
          description: The API path where the error occurred.
        status:
          type: integer
          description: HTTP status code of the error.
        statusCode:
          type: integer
          description: HTTP status code of the error.
        error:
          type: string
          description: Description of the error.
        message:
          type: string
          description: Description of the error.
        requestId:
          type: string
          description: Unique identifier for the request.
      example:
        timestamp: "2024-12-31T09:54:01.763+00:00"
        path: "/activations"
        status: 415
        error: "Unsupported Media Type"
        requestId: "3fb00d0f-416"

    # ------------------------------------------------------
    # Domain specific complex types.
    # ------------------------------------------------------
    Activation:
      allOf:
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ActivationId'
            effectiveActivationDate:
              $ref: '#/components/schemas/EffectiveActivationDate'
          required:
            - id
            - effectiveActivationDate
        - $ref: '#/components/schemas/ActivationReq'
      example:
        id: "d0d654e6-97da-4848-b568-99fedccb642b"
        effectiveActivationDate: "2024-10-30T16:39:34+01:00"
        payer:
          fiscalCode: "RSSMRA85T10A562S"
          rtpSpId: "12345678911"

    Activations:
      description: List of RTP activations.
      type: array
      minItems: 0
      maxItems: 128
      items:
        $ref: '#/components/schemas/Activation'
      example:
        - id: "d0d654e6-97da-4848-b568-99fedccb642b"
          effectiveActivationDate: "2024-10-30T16:39:34+01:00"
          payer:
            fiscalCode: "RSSMRA85T10A562S"
            rtpSpId: "12345678911"

    ActivationReq:
      description: |
        Data of a RTP activation.
      type: object
      #additionalProperties: true # It's extended by another object.
      properties:
        payer:
          $ref: '#/components/schemas/Payer'
      required:
        - payer
      example:
        payer:
          fiscalCode: "RSSMRA85T10A562S"
          rtpSpId: "12345678911"
  
    PageOfActivations:
      description: Page of RTP activations.
      type: object
      additionalProperties: false
      properties:
        activations:
          $ref: '#/components/schemas/Activations'
        page:
          $ref: '#/components/schemas/PageMetadata'
      required:
        - activations
        - page
      example:
        activations:
          - id: "d0d654e6-97da-4848-b568-99fedccb642b"
            effectiveActivationDate: "2024-10-30T16:39:34+01:00"
            payer:
              fiscalCode: "RSSMRA85T10A562S"
              rtpSpId: "12345678911"
        page:
          totalElements: 2
          totalPages: 2
          page: 1
          size: 1

    Payer:
      description: |
        Payer data.
      type: object
      additionalProperties: false
      properties:
        fiscalCode:
          $ref: '#/components/schemas/FiscalCode'
        rtpSpId:
          $ref: '#/components/schemas/PartyId'
      required:
        - fiscalCode
        - rtpSpId
      example:
        fiscalCode: "RSSMRA85T10A562S"
        rtpSpId: "12345678911"

    TakeoverActivationReq:
      description: Data to takeover a RTP activation.
      type: object
      additionalProperties: false
      properties:
        rtpSpId:
          $ref: '#/components/schemas/PartyId'
      required:
        - rtpSpId
      example:
        rtpSpId: "12345678911"

  # ============================================================================
  # Request bodies.
  # ============================================================================
  requestBodies:
    CreateOrUpdateActivation:
      description: Request to create or update a RTP activation.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivationReq'

    TakeoverActivation:
      description: Request to take over an existing RTP activation.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TakeoverActivationReq'

  # ============================================================================
  # Parameters.
  # ============================================================================
  parameters:
    ActivationId:
      name: activationId
      in: path
      description: Identifier of the RTP activation resource.
      required: true
      schema:
        $ref: '#/components/schemas/ActivationId'

    PageNumber:
      name: page
      in: query
      description: Number of the requested page of data.
      required: true
      schema:
        $ref: '#/components/schemas/PageNumber'

    PageSize:
      name: size
      in: query
      description: Size of the requested page of data.
      required: true
      schema:
        $ref: '#/components/schemas/PageSize'

    PayerId:
      name: PayerId
      in: header
      description: Identifier of the Payer.
      required: true
      schema:
        $ref: '#/components/schemas/FiscalCode'

    RequestId:
      name: RequestId
      in: header
      description: Identifier of the request.
      required: true
      schema:
        $ref: '#/components/schemas/RequestId'

    Version:
      name: Version
      in: header
      description: Version of the required API.
      required: false
      schema:
        $ref: '#/components/schemas/Version'

  # ============================================================================
  # Responses
  # ============================================================================
  responses:
    Activation:
      description: Response returned when RTP activation data is requested.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Activation'

    CreateActivation:
      description: Response returned when a RTP activation is requested.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Location:
          description: URL of the activation resource.
          required: true
          schema:
            $ref: '#/components/schemas/ActivationLocation'

    UnauthorizedError:
      description: Response returned when the credentials of the user are missing or invalid.
      headers:
        WWW-Authenticate: 
          description: |
            Indicates the authentication scheme(s) and parameters required to access a protected resource.
          required: false
          schema:
            $ref: '#/components/schemas/WWWAuthenticate'
      content:
        text/*:
          schema:
            type: string
            pattern: "^[ -~]{0,65535}$"
            maxLength: 65535

    ForbiddenError:
      description: Response returned when the user does not have the right permissions.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'

    ConflictError:
      description: Response returned when a RTP payer is already active.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Location:
          description: URL of the conflicting activation resource.
          required: true
          schema:
            $ref: '#/components/schemas/ActivationLocation'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'

    Error:
      description: Response returned when an error occurred.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Retry-After:
          description: |
            The number of seconds to wait before allowing a follow-up request.
          required: false
          schema:
            $ref: '#/components/schemas/RetryAfter'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
        text/*:
          schema:
            type: string
            pattern: "^[ -~]{0,65535}$"
            maxLength: 65535

    GenericError:
      description: Generic Error response.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
        Retry-After:
          description: |
            The number of seconds to wait before allowing a follow-up request.
          required: false
          schema:
            $ref: '#/components/schemas/RetryAfter'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'
        text/*:
          schema:
            type: string
            pattern: "^[ -~]{0,65535}$"
            maxLength: 65535

    NoContent:
      description: No content response.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'

    PageOfActivations:
      description: Response to the request to get RTP activations.
      headers:
        Access-Control-Allow-Origin:
          description: |
            Indicates whether the response can be shared with requesting code
            from the given origin.
          required: false
          schema:
            $ref: '#/components/schemas/AccessControlAllowOrigin'
        RateLimit-Limit:
          description: The number of allowed requests in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitLimit'
        RateLimit-Reset:
          description: The number of seconds left in the current period.
          required: false
          schema:
            $ref: '#/components/schemas/RateLimitReset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageOfActivations'

  # ============================================================================
  # Security schemes.
  # ============================================================================
  securitySchemes:
    oAuth2:
      description: |
        A bearer token in the format of a JWS and conforms to the specifications
        included in RFC8725.
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /token
          refreshUrl: /token
          scopes:
            admin_rtp_activations: Admin RPT activation.
            write_rtp_activations: Create, update or delete RTP activation.
            read_rtp_activations: Read RTP activation.
